version: "3"

volumes:
  collabora-app:

networks:
  proxy:
    external: true
    name: shared-proxy

services:
  # collabora itself
  collabora-app:
    image: collabora/code:latest
    restart: always
    volumes:
      - collabora-app:/var/www/html:z
    cap_add:
      - MKNOD
    environment:
      - aliasgroup1=https://cloud\\.queerreferat\\.ac:443
      - ssl.enable=false
      - ssl.termination=true

  # web server for collabora
  collabora-server:
    build: ./collabora-server
    restart: always
    volumes:
      - collabora-app:/var/www/html:z,ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabora.rule=Host('office.queerreferat.ac')"
    depends_on:
      - collabora-app
    networks:
      - proxy
      - default

  # a separate nginx server might be needed
